{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "workflow.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ index .Values.depServices "class-443" "ingressClass" }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: doc-audit-mobile
            port:
              number: 3048
        path: /doc-audit-mobile
        pathType: Prefix
      - backend:
          service:
            name: doc-audit-client
            port:
              number: 1105
        path: /doc-audit-client
        pathType: Prefix
      - backend:
          service:
            name: workflow-manage-front
            port:
              number: 1110
        path: /workflow-manage-front
        pathType: Prefix
      - backend:
          service:
            name: workflow-manage-client
            port:
              number: 1104
        path: /workflow-manage-client
        pathType: Prefix
      - backend:
          service:
            name: flow-audit-core
            port:
              number: 9802
        path: /api/doc-audit-rest
        pathType: Prefix
      - backend:
          service:
            name: flow-audit-config
            port:
              number: 9800
        path: /api/workflow-rest
        pathType: Prefix
{{- end }}